// let a = 10;
// let b = 8457.7576;
// console.log(b);  type number
// console.log(b.toString()); convert into string 


// console.log(b.toFixed(3));  point ka bad wali  number ka batata ha output: 8457.7576
// console.log(typeof b.toFixed(1));  return in string

// console.log(b.toPrecision(5)); total display num ka batata ha is ma point ko count nahi kia jata e.g: 8457.7 return in string
  
// another method to create the number 
// ya wala method zaida use nahi hota bus reare cases ma use hota ha 
// let a = new Number(29);
// console.log(typeof a);   ya object ma value ko return karta ha 


                        // math 
// console.log(Math.PI);
// console.log(Math.LOG2E);  we can use more function of math 
// console.log(Math.floor(3.2));  output will be 3
// console.log(Math.ceil(3.2));    output will be 4

    // ---math.random 
// console.log(Math.random());  it will generate random value from 0 to 1 but 1 will be exclude 

// console.log(Math.random()*10); it generate value from 0 to 10 exclude 10 
// console.log(Math.floor(Math.random()*10)+1); it generate value from 1 to 10,

    // generate value ftom 15 to 25 
// console.log(Math.floor(Math.random()*11)+15);
        //  formula
// Math.floor(Math.random()*(min-max+1)+min)

// for(let n = 0; n <= 10; n++)
// {
//     let min = 15;
//     let max = 25;
//    console.log(Math.floor(Math.random()*(max-min+1)+min));
    
// }
// OTP generated by Math.random is not secure 